[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = ""
email = ""

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
databaseName = "GopherAI"
charset =  "utf8mb4"

[jwtConfig]
expire_duration= 8760
issuer= "huanheart"
subject= "GopherAI"
key= "CHANGE_ME"

[rabbitmqConfig]
host= "127.0.0.1"
port= 5672
username= "root"
password= ""
vhost= "/"
